//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace SQLAppStadi
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Concession>();
                db.CreateTable<ConcessionItem>();
                db.CreateTable<Item>();
                db.CreateTable<Order>();
                db.CreateTable<Seats>();
                db.CreateTable<Stadium>();
                db.CreateTable<User>();
            }
        }
    }
    public partial class Concession
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Name { get; set; }
        
        public Int64 Section { get; set; }
        
    }
    
    public partial class ConcessionItem
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        
        public int ConcessionId { get; set; }
        
        public int ItemId { get; set; }
        
    }
    
    public partial class Item
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        
        public string ItemName { get; set; }
        
        public double Price { get; set; }
        
        public string Image { get; set; }
        
    }
    
    public partial class Order
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        
        
        public int UserId { get; set; }
        
        public int ItemId { get; set; }
        
        public int Completed { get; set; }
        
    }
    
    public partial class Seats
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        
        public int Section { get; set; }
        
        public int Row { get; set; }
        
        public int Seat { get; set; }
        
    }
    
    public partial class Stadium
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        
        public string StadiumName { get; set; }
        
        public string Address { get; set; }
        
        public string City { get; set; }
        
        public string State { get; set; }
        
        public int Zipcode { get; set; }
        
        public string Image { get; set; }
        
    }
    
    public partial class User
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        
        public string Username { get; set; }
        
        public string Password { get; set; }
        
    }
    
}
